Верстка главной страницы
htmlacademy-adaptive/1959447-pognali-25 pull request #2
Opened 2022-04-01 19:01 UTC by ElenaMihailova

2022-04-02 16:32 UTC, nikopol-fw requested changes

2022-04-02 16:32 UTC, nikopol-fw commented on source/index.html
> +        </ul>
А зачем оно тут, дублирование?
Во-первых тот же вопрос насчет списка.
Во-вторых лучше разметить своими классами. Отличаются же.
p.s. можно оставить на потом. Вообще вопрос классов будет понятнее при стилизации

2022-04-02 16:32 UTC, nikopol-fw commented on source/index.html
> +          <p class="review__author">Мурат&nbsp;Эльтазин главный&nbsp;редактор газеты&nbsp;&laquo;гаджетлайф&raquo;</p>
В этом месте вместо `p` хорошо зайдет `cite` — источник цитирования

2022-04-02 16:32 UTC, nikopol-fw commented on source/index.html
> +      <!-- Это список? -->
Это список?) Ну список же — одно направление, второе, третье и т.д. Показать все. Несколько сущностей одного типа — список

2022-04-02 16:32 UTC, nikopol-fw commented on source/index.html
> +        <p class="cards__amount">18321</p>
Давай попробуем сделать красиво, порядок элементов как в нормально документе:
- заголовок
- флаг
- фото
- описание
- количество со скрытым пояснением внутри "Количество путешественников: "

<details>
<summary>Пример кода, спойлер</summary>


```html
<p class="cards__amount"><span class="visually-hidden">Количество путешественников: </span>18321</p>
```

</details>

2022-04-02 16:32 UTC, nikopol-fw commented on source/index.html
> +      <a class="destination__button button-all" href="#">Показать всё</a>
Вряд ли `button-all`. Просто button, но с модификатором для иконки ;)

2022-04-02 16:32 UTC, nikopol-fw commented on source/index.html
> +          <h3 class="cards__name">Таня Фирсова</h3>
Давай имя обернем в ссылку, иначе смысл от блока? Почитать интересно, но тут как то выбрать попутчика надо.
Потом из этой ссылки будем делать магию

2022-04-02 16:32 UTC, nikopol-fw commented on source/index.html
> +          <img class="cards__img-flag" src="image/seychelles.jpg" alt="Флаг Республики Сейшельские острова.">
В список и каждый флаг обернуть в ссылку. alt ты описала верно, но думаю можно его использовать как описание для ссылки, потому просто название страны

2022-04-02 16:32 UTC, nikopol-fw commented on source/index.html
> +          <p class="cards__tag">#ЗОЖ #ПП #Фитнес #пляж#авокадо #смузи</p>
Разбить на список, каждый хэштег обернуть в ссылку. Если в хэштег нельзя тыкнуть, то от него нет особого смысла

2022-04-02 16:32 UTC, nikopol-fw commented on source/index.html
> +          <p class="cards__icon"> Список доступных средств передвижения
Еще список, с содержимым и заголовком. Все слова скрыть

2022-04-02 16:32 UTC, nikopol-fw commented on source/index.html
> +      </ul>
Нужно переделать на dl, dt, dd. Иначе плохая связность. `<p>Бесплатно</p>` — что бесплатно? Глазами видно, по структуре нет.
https://htmlacademy.ru/courses/301/run/6

2022-04-02 16:32 UTC, nikopol-fw commented on source/index.html
> +    </section>
Давай объединим блоки? Смысл же об одном — как связаться.
Заинтересовались — по смысл на заголовок не тянет. Скорее это контакты

**upd** точнее перенести в верхний блок вопрос, телефон и емейл. Адрес в нижний

2022-04-06 17:21 UTC, nikopol-fw approved these changes

2022-04-06 17:21 UTC, merged

2022-08-10 10:09 UTC, Volnodoom commented on source/index.html
> +          <h3 class="cards__name">Таня Фирсова</h3>
Добрый день, коллеги  @nikopol-fw  и @ElenaMihailova . 
А мне вот интересно, почему вы в данном разделе вставляете/верстаете карточки, а не используете вставку по картинке (<img>)? 
Ведь этот раздел похоже больше на рекламу нежели на что-то с чем следует взаимодействовать.

2022-08-10 17:46 UTC, ElenaMihailova commented on source/index.html
> +          <h3 class="cards__name">Таня Фирсова</h3>
@Volnodoom предполагаю что при работе сайта, карточка на главной генерируется из живых данных пользователей.  Пользователь добавил еще пять стран, поменял фотку, и если его карточка (профиль) был представлен на любой странице сайта то также изменяется. 
Вставка по картинке как реализуется? Откуда берется картинка с наполненной карточкой?

2022-08-11 04:53 UTC, Volnodoom commented on source/index.html
> +          <h3 class="cards__name">Таня Фирсова</h3>
@ElenaMihailova привет, имел ввиду вставку картинки, через тег img. А сама карточка, это как реклама. и она не завязана на реальных пользователях. Но обратив внимание на требование в стайлинге, понял, что они хотят чтобы карточка была сверстана.