Module2 task2
htmlacademy-adaptive/1959447-pognali-25 pull request #3
Opened 2022-04-06 13:24 UTC by ElenaMihailova

2022-04-08 20:07 UTC, ElenaMihailova commented
Добавлена разметка формы и каталога

2022-04-10 16:35 UTC, nikopol-fw requested changes

2022-04-10 16:35 UTC, nikopol-fw commented on source/catalog.html
> +            <button class="continent__button">Острова</button>
Кнопки без `type` уже плохо.
Предлагаю вовсе заменить на ссылки с якорями. Типичная реализация табов через ссылки, если представить, что все списки не будут скрыты и не будет реализации через js, то табы это как оглавление в начале большой страницы.

2022-04-10 16:35 UTC, nikopol-fw commented on source/catalog.html
> +              <button class="select-country__alphabet-letter select-country__alphabet-letter--current">А</button>
Всем кнопка указать строго `type`

2022-04-10 16:35 UTC, nikopol-fw commented on source/catalog.html
> +                <li class="country-all__list-item">Афганистан</li>
Без интерактивных элементов от этого списка нет смысла. Думаю, тут следует сделать ссылки

2022-04-10 16:35 UTC, nikopol-fw commented on source/catalog.html
> +          <button class="location__button">Свернуть</button>
`type`, `type` и еще раз `type`
Больше на эту тему оставлять комментарии не буду, просто. строго: **всем** кнопкам всегда указывать тип

2022-04-10 16:35 UTC, nikopol-fw commented on source/catalog.html
> +        <div class="catalog-traveler__filter-person companion-selection">
Может все же тут отдельная секция? Какой смысл всё вообще оборачивать в одну большую секцию. Это тоже самое, что вовсе не создавать секции, всё оставить в одном main. Вполне себе выбор страны и фильтрация внутри страны два отдельных крупных блока. У тебя даже заголовок ниже есть, причем h2

2022-04-10 16:35 UTC, nikopol-fw commented on source/catalog.html
> +            <a class="form-filter__button button" href="#">Показать</a>
Ну тут то конечно кнопка submit. Это же форма, как мы иначе данные отправим из input'ов?

2022-04-10 16:35 UTC, nikopol-fw commented on source/catalog.html
> +      <div class="catalog-traveler__offers">
Тут напрашивается секция. Блок непосредственно с самим списком попутчиков

2022-04-10 16:35 UTC, nikopol-fw commented on source/catalog.html
> +              <h2 class="cards-person__name">Таня Фирсова</h2>
Ну а тут конечно h3, ведь это маленькие элементы в большом списке. Это по любому не крупные блоки все страницы. Ведь сам попутчик является частью группы попутчиков, что уже должно подводить к идее о выделении более низкого уровня

2022-04-10 16:35 UTC, nikopol-fw commented on source/catalog.html
> +            <img class="cards-person__img" src="image/tanya.jpg" alt="Таня Фирсова." />
Давай сделаем красивый порядок, логичный. Сперва заголовок, потом все остальное. Чтобы страница без стилей выглядел прям как нормальный документ
![image](https://user-images.githubusercontent.com/22588831/162629590-6aa82c96-ab39-4c1e-9d80-390f01522897.png)

2022-04-10 16:35 UTC, nikopol-fw commented on source/catalog.html
> +              </button>
Следует добавить описание для кнопки

2022-04-10 16:35 UTC, nikopol-fw commented on source/catalog.html
> +            <button class="cards-person__button button">Позвать!</button>
Думаю ссылку надо делать. Формы нет, данные никакие не отправляем и не запрашиваем.

2022-04-10 16:35 UTC, nikopol-fw commented on source/catalog.html
> +        <a class="catalog-traveler__offers-button button-all" href="#">Показать еще</a>
Скорее кнопка чем ссылка. Без js такое работать не будет

2022-04-10 16:35 UTC, nikopol-fw commented on source/catalog.html
> +          class="catalog-traveler__offers-pagination  catalog-traveler__offers-pagination--next">Следующая</button>
Скорее ссылки чем кнопка, Переход на другую страницу с продолжением списка попудчиков по параметрам в url'е

2022-04-11 20:35 UTC, nikopol-fw requested changes

2022-04-11 20:35 UTC, nikopol-fw commented on source/catalog.html
> +            <label class="continent__title vissually-hidden">Выбор части света</label>
label для чего тут? input'ов нет. Если label ни с чем не связан через вложенность или `for`, то он ничего не описывает. Вообще предлагаю убрать сей тег.

2022-04-11 20:35 UTC, nikopol-fw commented on source/catalog.html
> +        <fieldset class="catalog-traveler__filter-location location">
Всё-таки место fieldset в формах, ну или хотя бы чтобы внутри были input'ы. В данном случае нет ничего. Подозрительно даже то, что fieldset один. То есть fieldset выделяет группу полей, но если все элементы одна большая группа, зачем что-то выделять? Эту роль уже выполняет section. Верни div

2022-04-11 20:35 UTC, nikopol-fw commented on source/catalog.html
> +                  <img class="flag-country__img" src="image/sri-lanka.jpg" alt="Шри-Ланка.">
Смотри по описанию в alt получается дублирование контента в ссылке выше. Думаю, что не стоит делать флаги через img, проще и лучше потом на css фоном сделать

2022-04-12 18:40 UTC, nikopol-fw approved these changes

2022-04-13 00:32 UTC, merged